name: CI

on:
  push:
    branches: [ main, develop, dev, feature/** ]
  pull_request:
    branches: [ main, develop ]

# 👇 nécessaire pour pouvoir pousser/ouvrir une PR
permissions:
  contents: write
  pull-requests: write

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Ruff + Black check
        run: |
          ruff check .
          black --check .
      - name: Unit tests (non-Blender)
        run: pytest -q

  yaml-generate-validate:
    runs-on: ubuntu-latest
    needs: [lint-and-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Generate voice configs (multi-lang)
        run: |
          python scripts/ggenerate_voice_config.py
      - name: Validate voice configs
        run: |
          python scripts/validate_voice_config.py

      - name: Upload generated YAML
        uses: actions/upload-artifact@v4
        with:
          name: voice-configs
          path: |
            ares/config/voice_config.yaml
            ares/config/voice_config_*.yaml

      # ✅ commit auto + PR ci/auto-yaml → main
      - name: Commit generated YAML
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B ci/auto-yaml
          git add ares/config/voice_config.yaml ares/config/voice_config_*.yaml || true
          git commit -m "chore(ci): update voice_config (auto)" || echo "No changes"

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/auto-yaml
          title: "chore(ci): update voice_config (auto)"
          body: "Generated by CI."
          commit-message: "chore(ci): update voice_config (auto)"
          delete-branch: true

  build-zip:
    runs-on: ubuntu-latest
    needs: [yaml-generate-validate]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build addon zip
        run: |
          python scripts/build_zip.py
      - name: Upload addon zip
        uses: actions/upload-artifact@v4
        with:
          name: blade-addon-zip
          path: dist/*.zip

  blender-smoke:
    # job optionnel : tourne seulement si BLENDER_URL est définie (variable de repo)
    if: ${{ vars.BLENDER_URL != '' || env.BLENDER_URL != '' }}
    runs-on: ubuntu-latest
    needs: [build-zip]
    env:
      BLENDER_URL: ${{ vars.BLENDER_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Download Blender (if BLENDER_URL provided)
        run: |
          echo "BLENDER_URL=$BLENDER_URL"
          curl -L "$BLENDER_URL" -o blender.tar.xz
          mkdir blender && tar -xJf blender.tar.xz -C blender --strip-components=1
          echo "$GITHUB_WORKSPACE/blender" >> $GITHUB_PATH
      - name: Smoke test in headless Blender
        run: |
          ./blender/blender --version
          ./blender/blender --background --factory-startup --python scripts/blender/smoke_test.py
