name: Release

on:
  push:
    tags: ['v*']

jobs:
  build-release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Generate + Validate YAML
        run: |
          python -m pip install pyyaml
          python scripts/generate_voice_config.py
          python scripts/validate_voice_config.py
      - name: Build zip
        run: |
          python scripts/build_zip.py
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
